dataset:
  name: cylinderflow
  dir: /media/user/HDD-UT/rajarshi_data/cylinder_flow_deepmind/cylinder_flow/
  meta: meta.json
  train: train.tfrecord
  valid: valid.tfrecord
  test: test.tfrecord

model:
  latent_dim: 128
  message_passing_steps: 15

train:
  seed: 42
  learning_rate: 1e-4
  steps: 5000
  steps_per_log: 100
  log: logs/base.csv
  ckpt_dir: /media/user/HDD-UT/rajarshi_data/gnn_jax_eg/train

eval:
  ckpt_dir: /media/user/HDD-UT/rajarshi_data/gnn_jax_eg/train
  eval_dir: /media/user/HDD-UT/rajarshi_data/gnn_jax_eg/eval
  log: logs/base_eval.csv
